# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sunrise-scaffold}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Igor Galeta", "Pavlo Galeta"]
  s.date = %q{2011-05-17}
  s.description = %q{Sunrise is a Aimbulance CMS}
  s.email = %q{galeta.igor@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "Rakefile",
    "lib/generators/sunrise_scaffold/USAGE",
    "lib/generators/sunrise_scaffold/manage_generator.rb",
    "lib/generators/sunrise_scaffold/templates/multiplay/controller.rb",
    "lib/generators/sunrise_scaffold/templates/multiplay/functional_test.rb",
    "lib/generators/sunrise_scaffold/templates/multiplay/helper.rb",
    "lib/generators/sunrise_scaffold/templates/multiplay/views/edit.html.erb",
    "lib/generators/sunrise_scaffold/templates/multiplay/views/form.html.erb",
    "lib/generators/sunrise_scaffold/templates/multiplay/views/index.html.erb",
    "lib/generators/sunrise_scaffold/templates/multiplay/views/item.html.erb",
    "lib/generators/sunrise_scaffold/templates/multiplay/views/model_filter.html.erb",
    "lib/generators/sunrise_scaffold/templates/multiplay/views/new.html.erb",
    "lib/generators/sunrise_scaffold/templates/multiplay/views/show.html.erb",
    "lib/generators/sunrise_scaffold/templates/single/controller.rb",
    "lib/generators/sunrise_scaffold/templates/single/functional_test.rb",
    "lib/generators/sunrise_scaffold/templates/single/helper.rb",
    "lib/generators/sunrise_scaffold/templates/single/views/edit.html.erb",
    "lib/generators/sunrise_scaffold/templates/single/views/form.html.erb",
    "lib/generators/sunrise_scaffold/templates/single/views/index.html.erb",
    "lib/generators/sunrise_scaffold/templates/single/views/item.html.erb",
    "lib/generators/sunrise_scaffold/templates/single/views/model_filter.html.erb",
    "lib/generators/sunrise_scaffold/templates/single/views/new.html.erb",
    "lib/generators/sunrise_scaffold/templates/single/views/show.html.erb",
    "lib/sunrise_scaffold.rb",
    "lib/sunrise_scaffold/utils.rb",
    "lib/sunrise_scaffold/version.rb"
  ]
  s.homepage = %q{https://github.com/galetahub/sunrise-scaffold}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Rails CMS}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

